import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Input from '../components/textInput';
import Dropdown from '../components/dropDown';
import RadioGroup from '../components/radioGroup';

export default function Home() {
  const colors = [
    { label: 'Red', value: 'red' },
    { label: 'Green', value: 'green' },
    { label: 'Blue', value: 'blue' },
  ];

  const seasons = [
    { label: 'Spring', value: 'spring', id: 'spring', name: 'seasons' },
    { label: 'Summer', value: 'summer', id: 'summer', name: 'seasons' },
    { label: 'Fall', value: 'fall', id: 'fall', name: 'seasons' },
  ];

  let formData = {};

  function myCallback(e) {
    formData[e.item] = e.value;
    console.log(formData);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Forms - USWDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <form>
          <div>
            <Input
              label="Enter your name"
              placeholder=""
              id="fullName"
              callback={myCallback}
            />
          </div>

          <div>
            <Dropdown
              label="Favorite color"
              id="favoriteColor"
              options={colors}
              callback={myCallback}
            />
          </div>

          <div>
            <RadioGroup
              id="seasons"
              label="Pick a season"
              options={seasons}
              callback={myCallback}
            />
          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
